### ISSUE TITLE
Plugin ignores installed vue2-leaflet

### ISSUE THREAD

**Issue by dnasir** [jperelli/vue2-leaflet-googlemutant#9]
Despite having installed the latest version of leaflet, this plugin continues to use an older version instead, overriding whatever version I have installed in my project.

Steps to reproduce:

1. Create a new Vue project using `vue create`.
2. Install latest versions of `leaflet` (1.4.0) and `vue2-leaflet` (2.1.1).
3. Install latest version of `vue2-leaflet-googlemutant`.
4. Run project using `npm run serve`.
5. Open browser console (F12).
6. Type `L`.
7. You will see something like this `{version: "1.3.1", noConflict: ƒ, Control: ƒ, control: ƒ, Browser: {…}, …}` in the console.

As you can see, the global version is `1.3.1`, instead of `1.4.0`. A simple solution to this would be to use `peerDependencies` instead, and let the developers decide which version they want to use.

**Comment by jperelli** [comment]
Yes, the problem is that the newer leaflet version is using ES6 import/export modules, but this particular plugin has not yet migrated to that kind of architecture. You can see here for example markercluster plugin using ES6 export https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/index.js , and here googlemutant plugin using the old leaflet way to add a plugin by mutating the global `L` object https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/blob/master/Leaflet.GoogleMutant.js

In order to be able to use leaflet >= 1.3.2 with a leaflet-plugin you would need the plugin to export ES6 modules instead of mutating the global `L` object. This issue has been largely discussed in a vue2-leaflet issue. see https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md#es6--rollup

What we could do is to make a PR to upgrade googlemutant plugin to export ES6 modules.

**Comment by dnasir** [comment]
Sounds good. I'll see if I can contribute in that direction.

**Comment by dnasir** [comment]
Quick update. I've tested this plugin with the latest versions of leaflet and googlemutant, and everything worked as expected. It doesn't look like we need to wait for googlemutant to migrate to es6 for this plugin to work with the latest versions of leaflet and googlemutant. This is most likely due to the plugin calling `L.gridLayer.googleMutant` instead of new-ing up.

Is it really necessary for us to wait for googlemutant to migrate to es6 before proceeding?

**Comment by jeancaffou** [comment]
Can confirm that it works if you update vue2-leaflet to the latest version and use the package.json fix from #10, as described in my comment in issue #11
